update generate-completion

diff --git a/generate-completion b/generate-completion
--- a/generate-completion
+++ b/generate-completion
@@ -1,16 +1,20 @@
 #!/usr/bin/env bash
 
-set -euo pipefail
+set -eo pipefail
 
 declare -A default_completion_dir
 default_completion_dir[bash]="${HOME}/.local/share/bash-completion/completions"
 default_completion_dir[zsh]="${HOME}/.local/share/zsh/completions"
 
 declare -A completion_generator_command_template
+completion_generator_command_template[apt-fast]="curl -fsSL https://raw.githubusercontent.com/ilikenwf/apt-fast/master/completions/{shell}/{filename}"
 completion_generator_command_template[chezmoi]="{program} completion {shell}"
-completion_generator_command_template[gh]="{program} completion --shell {shell}"
 completion_generator_command_template[docker-compose]="curl -fsSL https://raw.githubusercontent.com/docker/compose/1.25.5/contrib/completion/{shell}/{filename}"
+completion_generator_command_template[exa]="curl -fsSL https://raw.githubusercontent.com/ogham/exa/master/contrib/completions.{shell}"
+completion_generator_command_template[gh]="{program} completion --shell {shell}"
+completion_generator_command_template[lf]="curl -fsSL https://raw.githubusercontent.com/gokcehan/lf/master/etc/{program}.{shell}"
 completion_generator_command_template[snap]="curl -fsSL https://raw.githubusercontent.com/snapcore/snapd/master/data/completion/{shell}/{filename}"
+completion_generator_command_template[starship]="{program} completions {shell}"
 
 generate-completion() {
   local -r shell="${1}"
@@ -26,6 +30,13 @@ generate-completion() {
   generator_command="${generator_command/\{program\}/"${program}"}"
   generator_command="${generator_command/\{filename\}/"${filename}"}"
 
+  # fallback to shell specific ones
+  generator_command="${generator_command:-${completion_generator_command_template[${shell}:${program}]}}"
+
+  if [[ -z $generator_command ]]; then
+    echo "Couldn't resolve generator command!"
+    exit 1
+  fi
 
   read -rp "${shell} completion dir (default: ${default_completion_dir[${shell}]}): " completion_dir
   completion_dir="${completion_dir:-"${default_completion_dir[${shell}]}"}"
